apiVersion: apps/v1
kind: Deployment
metadata:
  name:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tidy-inventory
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - name: db
        image: postgres:12.6
        ports:
        - containerPort: 5432
      - name: nginx
          image: nginx:1.17.3
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-nginx-service
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: app-nginx