services:
  django:
    extends:
      file: docker-compose.yml
      service: django 
    command: ["tail", "-f", "/dev/null"]
    # command: ["./wait.sh", "python", "-m", "gunicorn", "-c", "/code/gunicorn/config.py", "tidy.asgi:application"]
    volumes:
      - django_vscode_extensions:/root/.vscode-server
  node:
    extends:
      file: docker-compose.yml
      service: node 
    volumes:
      - node_vscode_extensions:/root/.vscode-server
  db:
    extends:
      file: docker-compose.yml
      service: db 
  pgadmin:
    extends:
      file: docker-compose.yml
      service: pgadmin 
volumes:
  node_modules:
  dist:
  postgres:
  pgadmin-data:
  django_vscode_extensions:
  node_vscode_extensions: