# version: "3.7"
services:
  django:
    build: ./django
    image: tidy-django
    tty: true
    command: ["./wait.sh", "python", "manage.py", "runserver_plus", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./django/src:/code
    environment:
      - DJANGO_CONFIGURATION=dev
      - DB_HOST=db
    depends_on:
      - db
  node:
    build: ./node
    image: tidy-node
    tty: true
    command: ["npm", "run", "debug"]
    ports:
      - "8888:8888"
      - "9101:9101"
      - "9000:9000"
    volumes:
      - ./node/src:/code/
      - node_modules:/code/node_modules
  db:
    image: postgres:12.6
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./db/backups:/backups
    environment:
      - POSTGRES_USER=tidy
      - POSTGRES_PASSWORD=tidypass
  pgadmin:
    image: dpage/pgadmin4:2024-04-29-1
    ports:
      - "8181:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=tidy@domain.com
      - PGADMIN_DEFAULT_PASSWORD=tidypass
    # profiles: ["db_admin"]
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  node_modules:
  dist:
  postgres:
  pgadmin-data:
