apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tidy-db
spec:
  selector:
    matchLabels:
      app: postgres-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      volumes:
        - name: postgres-config
          configMap:
            name: postgres
      containers:
      - name: postgres-db
        image: postgres:12.6
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: app-nginx-service
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: app-nginx