# Generated by Django 2.2.4 on 2019-10-27 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('system_field', models.BooleanField(default=False)),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.House')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sublocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Location')),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('suffix', models.CharField(blank=True, default=None, max_length=200)),
                ('default_subType', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.SubType')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('default_tags', models.ManyToManyField(blank=True, null=True, to='core.TagType')),
                ('plane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Plane')),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(max_length=200)),
                ('labeled', models.BooleanField(default=False)),
                ('designated_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designated_things', to='core.Location')),
                ('designated_sublocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designated_things', to='core.Sublocation')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='things', to='core.Location')),
                ('subType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.SubType')),
                ('sublocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='things', to='core.Sublocation')),
                ('tags', models.ManyToManyField(blank=True, to='core.Tag')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Type')),
            ],
        ),
        migrations.AddField(
            model_name='tagtype',
            name='default_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Type'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tagType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.TagType'),
        ),
        migrations.AddField(
            model_name='subtype',
            name='default_tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.TagType'),
        ),
        migrations.AddField(
            model_name='subtype',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Type'),
        ),
        migrations.AddField(
            model_name='location',
            name='thing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equivalentLocation', to='core.Thing'),
        ),
        migrations.AddField(
            model_name='house',
            name='onwer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Owner'),
        ),
    ]
