# Generated by Django 2.2.4 on 2019-10-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_location_system_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='system_field',
            field=models.BooleanField(default=False),
        ),
    ]
