# Generated by Django 2.2.4 on 2019-10-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191027_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='system_field',
        ),
    ]
