# Generated by Django 4.1.3 on 2023-07-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_thing_description_alter_thing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtype',
            name='default_tags',
            field=models.ManyToManyField(blank=True, to='core.tagtype'),
        ),
        migrations.AlterField(
            model_name='type',
            name='default_tags',
            field=models.ManyToManyField(blank=True, to='core.tagtype'),
        ),
    ]
