# Generated by Django 4.1.3 on 2023-07-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_subtype_default_tags_alter_type_default_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
