# Generated by Django 4.1.3 on 2023-07-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_thing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
